[pytest]
markers =
    pta                         : UI tests for 'PTA' website
    heroku                      : UI tests for 'Heroku' website
    kwa                         : UI tests for 'KWA' app
    jsonplaceholder             : API tests for 'JSONPlaceholder'
    restcountries_data          : Data quality tests for REST Countries API
    excel                       : Read/Write data from/to an 'Excel file'
    param                       : Parametrized tests
    retry                       : Tests with retry logic